[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github.com/onedataengineer21/notebooks/blob/main/python/Exploring%20Chicago%20Crimes%20Data%202022.ipynb)



```
# This is formatted as code
```

Covid 19 was the biggest pandemic which was faced by the people for over a century. We again proved that humans cannot come together to solve a problem quickly. Millions of people lost their lives and livelihood and yet we all are living like nothing happened without being grateful for being alive today.

In [1]:
!python -m wget https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-counties-2020.csv
!python -m wget https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-counties-2021.csv
!python -m wget https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-counties-2022.csv
!python -m wget https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-counties-2023.csv

100% [....................................................] 35871900 / 35871900
Saved under us-counties-2020 (6).csv
100% [....................................................] 50311433 / 50311433
Saved under us-counties-2021 (6).csv
100% [....................................................] 51200840 / 51200840
Saved under us-counties-2022 (6).csv
100% [....................................................] 11541836 / 11541836
Saved under us-counties-2023 (6).csv

In [2]:
## importing the packages
import pandas as pd
import os
from pathlib import Path
import duckdb
import numpy as np
import sys
# Get the current working directory
current_working_directory = os.getcwd()

# Convert the current working directory to a Path object
script_dir = Path(current_working_directory)

In [4]:
%pip install jupysql --upgrade duckdb-engine pandas --quiet

Note: you may need to restart the kernel to use updated packages.

In [2]:
%reload_ext sql

/Users/beenapurushothama/anaconda3/lib/python3.11/site-packages/pandas/core/arrays/masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

Deploy Shiny apps for free on Ploomber Cloud! Learn more: https://ploomber.io/s/signup

### Loading the DUCKDB Engine

In [3]:
%sql duckdb:///covidandusa.duck.db

Connecting to 'duckdb:///covidandusa.duck.db'

### Creating the tables and loading the data

In [8]:
%%sql

create or replace table 
us_counties_2020 as
from read_csv_auto('us-counties-2020.csv', header=True)

Running query in 'duckdb:///covidandusa.duck.db'

+--------+
| Count  |
+--------+
| 884737 |
+--------+

In [9]:
%%sql

create or replace table 
us_counties_2021 as
from read_csv_auto('us-counties-2021.csv', header=True)

Running query in 'duckdb:///covidandusa.duck.db'

+---------+
|  Count  |
+---------+
| 1185373 |
+---------+

In [10]:
%%sql

create or replace table 
us_counties_2022 as
from read_csv_auto('us-counties-2022.csv', header=True)

Running query in 'duckdb:///covidandusa.duck.db'

+---------+
|  Count  |
+---------+
| 1188042 |
+---------+

In [11]:
%%sql

create or replace table 
us_counties_2023 as
from read_csv_auto('us-counties-2023.csv', header=True)

Running query in 'duckdb:///covidandusa.duck.db'

+--------+
| Count  |
+--------+
| 267009 |
+--------+

In [14]:
%%sql 

SHOW TABLES;

Running query in 'duckdb:///covidandusa.duck.db'

+------------------+
|       name       |
+------------------+
| us_counties_2020 |
| us_counties_2021 |
| us_counties_2022 |
| us_counties_2023 |
+------------------+

### JUPY SQLs TABLE EXPLORER

In [46]:
%sqlcmd explore --table us_counties_2020

In [48]:
%sqlcmd explore --table us_counties_2021

In [49]:
%sqlcmd explore --table us_counties_2022

In [47]:
%sqlcmd explore --table us_counties_2023

### Simple Queries - SELECT, FROM and LIMIT

In [15]:
%%sql
SELECT *
FROM us_counties_2020
LIMIT 5

Running query in 'duckdb:///covidandusa.duck.db'

+------------+-----------+------------+-------+-------+--------+
|    date    |   county  |   state    |  fips | cases | deaths |
+------------+-----------+------------+-------+-------+--------+
| 2020-01-21 | Snohomish | Washington | 53061 |   1   |   0    |
| 2020-01-22 | Snohomish | Washington | 53061 |   1   |   0    |
| 2020-01-23 | Snohomish | Washington | 53061 |   1   |   0    |
| 2020-01-24 |    Cook   |  Illinois  | 17031 |   1   |   0    |
| 2020-01-24 | Snohomish | Washington | 53061 |   1   |   0    |
+------------+-----------+------------+-------+-------+--------+

In [19]:
%%sql
SELECT *
FROM us_counties_2022
LIMIT 10

Running query in 'duckdb:///covidandusa.duck.db'

+------------+----------+---------+-------+-------+--------+
|    date    |  county  |  state  |  fips | cases | deaths |
+------------+----------+---------+-------+-------+--------+
| 2022-01-01 | Autauga  | Alabama | 01001 | 11018 |  160   |
| 2022-01-01 | Baldwin  | Alabama | 01003 | 39911 |  593   |
| 2022-01-01 | Barbour  | Alabama | 01005 |  3860 |   81   |
| 2022-01-01 |   Bibb   | Alabama | 01007 |  4533 |   95   |
| 2022-01-01 |  Blount  | Alabama | 01009 | 11256 |  198   |
| 2022-01-01 | Bullock  | Alabama | 01011 |  1676 |   46   |
| 2022-01-01 |  Butler  | Alabama | 01013 |  3613 |  102   |
| 2022-01-01 | Calhoun  | Alabama | 01015 | 23411 |  532   |
| 2022-01-01 | Chambers | Alabama | 01017 |  6171 |  147   |
| 2022-01-01 | Cherokee | Alabama | 01019 |  3385 |   65   |
+------------+----------+---------+-------+-------+--------+
Truncated to displaylimit of 10.

In [20]:
%%sql
SELECT date, state, county
FROM us_counties_2022
LIMIT 10

Running query in 'duckdb:///covidandusa.duck.db'

+------------+---------+----------+
|    date    |  state  |  county  |
+------------+---------+----------+
| 2022-01-01 | Alabama | Autauga  |
| 2022-01-01 | Alabama | Baldwin  |
| 2022-01-01 | Alabama | Barbour  |
| 2022-01-01 | Alabama |   Bibb   |
| 2022-01-01 | Alabama |  Blount  |
| 2022-01-01 | Alabama | Bullock  |
| 2022-01-01 | Alabama |  Butler  |
| 2022-01-01 | Alabama | Calhoun  |
| 2022-01-01 | Alabama | Chambers |
| 2022-01-01 | Alabama | Cherokee |
+------------+---------+----------+
Truncated to displaylimit of 10.

In [21]:
%%sql
SELECT date, state, county
FROM us_counties_2023
LIMIT 10

Running query in 'duckdb:///covidandusa.duck.db'

+------------+---------+----------+
|    date    |  state  |  county  |
+------------+---------+----------+
| 2023-01-01 | Alabama | Autauga  |
| 2023-01-01 | Alabama | Baldwin  |
| 2023-01-01 | Alabama | Barbour  |
| 2023-01-01 | Alabama |   Bibb   |
| 2023-01-01 | Alabama |  Blount  |
| 2023-01-01 | Alabama | Bullock  |
| 2023-01-01 | Alabama |  Butler  |
| 2023-01-01 | Alabama | Calhoun  |
| 2023-01-01 | Alabama | Chambers |
| 2023-01-01 | Alabama | Cherokee |
+------------+---------+----------+
Truncated to displaylimit of 10.

### Filtering queries

In [24]:
%%sql
SELECT *
FROM us_counties_2023
where county = 'Milwaukee'
LIMIT 10

Running query in 'duckdb:///covidandusa.duck.db'

+------------+-----------+-----------+-------+--------+--------+
|    date    |   county  |   state   |  fips | cases  | deaths |
+------------+-----------+-----------+-------+--------+--------+
| 2023-01-01 | Milwaukee | Wisconsin | 55079 | 332844 |  2431  |
| 2023-01-02 | Milwaukee | Wisconsin | 55079 | 332844 |  2431  |
| 2023-01-03 | Milwaukee | Wisconsin | 55079 | 333430 |  2431  |
| 2023-01-04 | Milwaukee | Wisconsin | 55079 | 333670 |  2435  |
| 2023-01-05 | Milwaukee | Wisconsin | 55079 | 333955 |  2440  |
| 2023-01-06 | Milwaukee | Wisconsin | 55079 | 334200 |  2440  |
| 2023-01-07 | Milwaukee | Wisconsin | 55079 | 334200 |  2440  |
| 2023-01-08 | Milwaukee | Wisconsin | 55079 | 334200 |  2440  |
| 2023-01-09 | Milwaukee | Wisconsin | 55079 | 334200 |  2440  |
| 2023-01-10 | Milwaukee | Wisconsin | 55079 | 334808 |  2442  |
+------------+-----------+-----------+-------+--------+--------+
Truncated to displaylimit of 10.

In [26]:
%%sql
SELECT *
FROM us_counties_2023
where county = 'Miami'
LIMIT 10

Running query in 'duckdb:///covidandusa.duck.db'

+------------+--------+---------+-------+-------+--------+
|    date    | county |  state  |  fips | cases | deaths |
+------------+--------+---------+-------+-------+--------+
| 2023-01-01 | Miami  | Indiana | 18103 | 10644 |  172   |
| 2023-01-01 | Miami  |  Kansas | 20121 |  9377 |  105   |
| 2023-01-01 | Miami  |   Ohio  | 39109 | 31066 |  503   |
| 2023-01-02 | Miami  | Indiana | 18103 | 10644 |  172   |
| 2023-01-02 | Miami  |  Kansas | 20121 |  9377 |  105   |
| 2023-01-02 | Miami  |   Ohio  | 39109 | 31066 |  503   |
| 2023-01-03 | Miami  | Indiana | 18103 | 10644 |  172   |
| 2023-01-03 | Miami  |  Kansas | 20121 |  9377 |  105   |
| 2023-01-03 | Miami  |   Ohio  | 39109 | 31066 |  503   |
| 2023-01-04 | Miami  | Indiana | 18103 | 10704 |  172   |
+------------+--------+---------+-------+-------+--------+
Truncated to displaylimit of 10.

In [27]:
%%sql
SELECT *
FROM us_counties_2023
where state = 'Florida'
LIMIT 10

Running query in 'duckdb:///covidandusa.duck.db'

+------------+-----------+---------+-------+--------+--------+
|    date    |   county  |  state  |  fips | cases  | deaths |
+------------+-----------+---------+-------+--------+--------+
| 2023-01-01 |  Alachua  | Florida | 12001 | 85571  |  796   |
| 2023-01-01 |   Baker   | Florida | 12003 | 10410  |  151   |
| 2023-01-01 |    Bay    | Florida | 12005 | 53685  |  886   |
| 2023-01-01 |  Bradford | Florida | 12007 |  8859  |  173   |
| 2023-01-01 |  Brevard  | Florida | 12009 | 168824 |  2443  |
| 2023-01-01 |  Broward  | Florida | 12011 | 746512 |  6565  |
| 2023-01-01 |  Calhoun  | Florida | 12013 |  4752  |  107   |
| 2023-01-01 | Charlotte | Florida | 12015 | 46183  |  971   |
| 2023-01-01 |   Citrus  | Florida | 12017 | 37671  |  1111  |
| 2023-01-01 |    Clay   | Florida | 12019 | 64775  |  954   |
+------------+-----------+---------+-------+--------+--------+
Truncated to displaylimit of 10.

In [30]:
%%sql
SELECT *
FROM us_counties_2023
where state = 'Wisconsin' and county = 'Waukesha'
LIMIT 10

Running query in 'duckdb:///covidandusa.duck.db'

+------------+----------+-----------+-------+--------+--------+
|    date    |  county  |   state   |  fips | cases  | deaths |
+------------+----------+-----------+-------+--------+--------+
| 2023-01-01 | Waukesha | Wisconsin | 55133 | 136982 |  1205  |
| 2023-01-02 | Waukesha | Wisconsin | 55133 | 136982 |  1205  |
| 2023-01-03 | Waukesha | Wisconsin | 55133 | 137199 |  1205  |
| 2023-01-04 | Waukesha | Wisconsin | 55133 | 137293 |  1206  |
| 2023-01-05 | Waukesha | Wisconsin | 55133 | 137367 |  1209  |
| 2023-01-06 | Waukesha | Wisconsin | 55133 | 137431 |  1209  |
| 2023-01-07 | Waukesha | Wisconsin | 55133 | 137431 |  1209  |
| 2023-01-08 | Waukesha | Wisconsin | 55133 | 137431 |  1209  |
| 2023-01-09 | Waukesha | Wisconsin | 55133 | 137431 |  1209  |
| 2023-01-10 | Waukesha | Wisconsin | 55133 | 137620 |  1210  |
+------------+----------+-----------+-------+--------+--------+
Truncated to displaylimit of 10.

In [36]:
%%sql
SELECT *
FROM us_counties_2023
where deaths > 44000
LIMIT 10

Running query in 'duckdb:///covidandusa.duck.db'

+------------+---------------+----------+------+---------+--------+
|    date    |     county    |  state   | fips |  cases  | deaths |
+------------+---------------+----------+------+---------+--------+
| 2023-01-04 | New York City | New York | None | 3141418 | 44033  |
| 2023-01-05 | New York City | New York | None | 3145225 | 44071  |
| 2023-01-06 | New York City | New York | None | 3149856 | 44101  |
| 2023-01-07 | New York City | New York | None | 3149856 | 44101  |
| 2023-01-08 | New York City | New York | None | 3149856 | 44101  |
| 2023-01-09 | New York City | New York | None | 3160133 | 44127  |
| 2023-01-10 | New York City | New York | None | 3162427 | 44178  |
| 2023-01-11 | New York City | New York | None | 3164400 | 44235  |
| 2023-01-12 | New York City | New York | None | 3167913 | 44265  |
| 2023-01-13 | New York City | New York | None | 3171129 | 44295  |
+------------+---------------+----------+------+---------+--------+
Truncated to displaylimit of 10.

In [39]:
%%sql
SELECT *
FROM us_counties_2023
where deaths < 40
LIMIT 10

Running query in 'duckdb:///covidandusa.duck.db'

+------------+-------------------------------------+---------+-------+-------+--------+
|    date    |                county               |  state  |  fips | cases | deaths |
+------------+-------------------------------------+---------+-------+-------+--------+
| 2023-01-01 |               Unknown               | Alabama |  None |  4703 |   0    |
| 2023-01-01 |        Aleutians East Borough       |  Alaska | 02013 |  1305 |   5    |
| 2023-01-01 |      Aleutians West Census Area     |  Alaska | 02016 |  1891 |   2    |
| 2023-01-01 | Bristol Bay plus Lake and Peninsula |  Alaska | 02997 |  1215 |   1    |
| 2023-01-01 |            Denali Borough           |  Alaska | 02068 |  1790 |   2    |
| 2023-01-01 |        Dillingham Census Area       |  Alaska | 02070 |  2211 |   14   |
| 2023-01-01 |            Haines Borough           |  Alaska | 02100 |  792  |   1    |
| 2023-01-01 |       Juneau City and Borough       |  Alaska | 02110 | 11669 |   27   |
| 2023-01-01 |      Ketchikan Gateway Borough      |  Alaska | 02130 |  5054 |   24   |
| 2023-01-01 |        Kodiak Island Borough        |  Alaska | 02150 |  5746 |   12   |
+------------+-------------------------------------+---------+-------+-------+--------+
Truncated to displaylimit of 10.

### Common Table Expressions

In [79]:
%%sql
-- Creating the table holding valus for Milwaukee in Wisconsin
WITH 
wisconsin_2020 AS (select * from us_counties_2020 where state = 'Wisconsin' and county = 'Milwaukee'),
wisconsin_2021 AS (select * from us_counties_2021 where state = 'Wisconsin' and county = 'Milwaukee'),
wisconsin_2022 AS (select * from us_counties_2022 where state = 'Wisconsin' and county = 'Milwaukee'),
wisconsin_2023 AS (select * from us_counties_2023 where state = 'Wisconsin' and county = 'Milwaukee'),
wisconsin AS (select * from wisconsin_2020 UNION select * from wisconsin_2021 UNION select * from wisconsin_2022 UNION select * from wisconsin_2023)

-- Creating new columns to hold the dailycases and deaths number
select *,  
       COALESCE(cases - lag(cases) OVER(ORDER BY DATE), 0) as DailyCases,
       COALESCE(deaths - lag(deaths) OVER(ORDER BY DATE), 0) as DailDeaths
from wisconsin
order by date

Running query in 'duckdb:///covidandusa.duck.db'

+------------+-----------+-----------+-------+-------+--------+------------+------------+
|    date    |   county  |   state   |  fips | cases | deaths | DailyCases | DailDeaths |
+------------+-----------+-----------+-------+-------+--------+------------+------------+
| 2020-03-13 | Milwaukee | Wisconsin | 55079 |   2   |   0    |     0      |     0      |
| 2020-03-14 | Milwaukee | Wisconsin | 55079 |   6   |   0    |     4      |     0      |
| 2020-03-15 | Milwaukee | Wisconsin | 55079 |   7   |   0    |     1      |     0      |
| 2020-03-16 | Milwaukee | Wisconsin | 55079 |   13  |   0    |     6      |     0      |
| 2020-03-17 | Milwaukee | Wisconsin | 55079 |   24  |   0    |     11     |     0      |
| 2020-03-18 | Milwaukee | Wisconsin | 55079 |   47  |   0    |     23     |     0      |
| 2020-03-19 | Milwaukee | Wisconsin | 55079 |   62  |   0    |     15     |     0      |
| 2020-03-20 | Milwaukee | Wisconsin | 55079 |   95  |   1    |     33     |     1      |
| 2020-03-21 | Milwaukee | Wisconsin | 55079 |  126  |   2    |     31     |     1      |
| 2020-03-22 | Milwaukee | Wisconsin | 55079 |  183  |   2    |     57     |     0      |
+------------+-----------+-----------+-------+-------+--------+------------+------------+
Truncated to displaylimit of 10.

#### Is there a county in Florida named Miami or Is Miami a Country in Florida

In [90]:
%%sql 
-- Is there a county in florida named Miami
select distinct county from us_counties_2020 where state = 'Florida' and county like 'M%'

Running query in 'duckdb:///covidandusa.duck.db'

+------------+
|   county   |
+------------+
|   Monroe   |
|  Manatee   |
| Miami-Dade |
|   Marion   |
|   Martin   |
|  Madison   |
+------------+

In [92]:
%%sql
-- Creating the table holding valus for Miami in Florida
WITH 
miami_2020 AS (select * from us_counties_2020 where state = 'Florida' and county = 'Miami-Dade'),
miami_2021 AS (select * from us_counties_2021 where state = 'Florida' and county = 'Miami-Dade'),
miami_2022 AS (select * from us_counties_2022 where state = 'Florida' and county = 'Miami-Dade'),
miami_2023 AS (select * from us_counties_2023 where state = 'Florida' and county = 'Miami-Dade'),
miami AS (select * from miami_2020 UNION select * from miami_2021 UNION select * from miami_2022 UNION select * from miami_2023)

-- Creating new columns to hold the dailycases and deaths number
select *,  
       COALESCE(cases - lag(cases) OVER(ORDER BY DATE), 0) as DailyCases,
       COALESCE(deaths - lag(deaths) OVER(ORDER BY DATE), 0) as DailDeaths
from miami
order by date

Running query in 'duckdb:///covidandusa.duck.db'

+------------+------------+---------+-------+-------+--------+------------+------------+
|    date    |   county   |  state  |  fips | cases | deaths | DailyCases | DailDeaths |
+------------+------------+---------+-------+-------+--------+------------+------------+
| 2020-03-11 | Miami-Dade | Florida | 12086 |   1   |   0    |     0      |     0      |
| 2020-03-12 | Miami-Dade | Florida | 12086 |   2   |   0    |     1      |     0      |
| 2020-03-13 | Miami-Dade | Florida | 12086 |   8   |   0    |     6      |     0      |
| 2020-03-14 | Miami-Dade | Florida | 12086 |   8   |   0    |     0      |     0      |
| 2020-03-15 | Miami-Dade | Florida | 12086 |   13  |   0    |     5      |     0      |
| 2020-03-16 | Miami-Dade | Florida | 12086 |   23  |   0    |     10     |     0      |
| 2020-03-17 | Miami-Dade | Florida | 12086 |   43  |   0    |     20     |     0      |
| 2020-03-18 | Miami-Dade | Florida | 12086 |   77  |   0    |     34     |     0      |
| 2020-03-19 | Miami-Dade | Florida | 12086 |  101  |   0    |     24     |     0      |
| 2020-03-20 | Miami-Dade | Florida | 12086 |  124  |   0    |     23     |     0      |
+------------+------------+---------+-------+-------+--------+------------+------------+
Truncated to displaylimit of 10.

In [96]:
%%sql
-- Creating the table holding valus for Illinois
WITH 
illinois_2020 AS (select * from us_counties_2020 where state = 'Illinois'),
illinois_2021 AS (select * from us_counties_2021 where state = 'Illinois'),
illinois_2022 AS (select * from us_counties_2022 where state = 'Illinois'),
illinois_2023 AS (select * from us_counties_2023 where state = 'Illinois'),
illinois AS (select * from illinois_2020 UNION select * from illinois_2021 UNION select * from illinois_2022 UNION select * from illinois_2023)

-- Creating new columns to hold the dailycases and deaths number
select *,  
       COALESCE(cases - lag(cases) OVER(ORDER BY COUNTY, DATE), 0) as DailyCases,
       COALESCE(deaths - lag(deaths) OVER(ORDER BY COUNTY, DATE), 0) as DailDeaths
from illinois
order by county, date

Running query in 'duckdb:///covidandusa.duck.db'

+------------+--------+----------+-------+-------+--------+------------+------------+
|    date    | county |  state   |  fips | cases | deaths | DailyCases | DailDeaths |
+------------+--------+----------+-------+-------+--------+------------+------------+
| 2020-03-20 | Adams  | Illinois | 17001 |   1   |   0    |     0      |     0      |
| 2020-03-21 | Adams  | Illinois | 17001 |   1   |   0    |     0      |     0      |
| 2020-03-22 | Adams  | Illinois | 17001 |   1   |   0    |     0      |     0      |
| 2020-03-23 | Adams  | Illinois | 17001 |   1   |   0    |     0      |     0      |
| 2020-03-24 | Adams  | Illinois | 17001 |   1   |   0    |     0      |     0      |
| 2020-03-25 | Adams  | Illinois | 17001 |   1   |   0    |     0      |     0      |
| 2020-03-26 | Adams  | Illinois | 17001 |   1   |   0    |     0      |     0      |
| 2020-03-27 | Adams  | Illinois | 17001 |   1   |   0    |     0      |     0      |
| 2020-03-28 | Adams  | Illinois | 17001 |   1   |   0    |     0      |     0      |
| 2020-03-29 | Adams  | Illinois | 17001 |   2   |   0    |     1      |     0      |
+------------+--------+----------+-------+-------+--------+------------+------------+
Truncated to displaylimit of 10.

### Answering the queries

### Top 10 Days with the highest number of deaths reported in IL

In [97]:
%%sql
-- Creating the table holding valus for Illinois
WITH 
illinois_2020 AS (select * from us_counties_2020 where state = 'Illinois'),
illinois_2021 AS (select * from us_counties_2021 where state = 'Illinois'),
illinois_2022 AS (select * from us_counties_2022 where state = 'Illinois'),
illinois_2023 AS (select * from us_counties_2023 where state = 'Illinois'),
illinois AS (select * from illinois_2020 UNION select * from illinois_2021 UNION select * from illinois_2022 UNION select * from illinois_2023)

-- Creating new columns to hold the dailycases and deaths number
select *,  
       COALESCE(cases - lag(cases) OVER(ORDER BY COUNTY, DATE), 0) as DailyCases,
       COALESCE(deaths - lag(deaths) OVER(ORDER BY COUNTY, DATE), 0) as DailDeaths
from illinois
order by DailDeaths desc

Running query in 'duckdb:///covidandusa.duck.db'

+------------+---------+----------+-------+---------+--------+------------+------------+
|    date    |  county |  state   |  fips |  cases  | deaths | DailyCases | DailDeaths |
+------------+---------+----------+-------+---------+--------+------------+------------+
| 2020-06-08 | Unknown | Illinois |  None |   724   |  178   |    640     |    178     |
| 2020-11-06 |   Cook  | Illinois | 17031 |  210266 |  5742  |    5289    |    168     |
| 2022-01-24 |   Cook  | Illinois | 17031 | 1063411 | 13568  |   19903    |    167     |
| 2020-05-13 |   Cook  | Illinois | 17031 |  56406  |  2589  |    936     |    140     |
| 2020-05-05 |   Cook  | Illinois | 17031 |  45223  |  1922  |    1508    |    120     |
| 2022-01-19 |   Cook  | Illinois | 17031 | 1021674 | 13272  |    6023    |    113     |
| 2020-04-28 |   Cook  | Illinois | 17031 |  33449  |  1457  |    1496    |    110     |
| 2020-05-07 |   Cook  | Illinois | 17031 |  48341  |  2110  |    1652    |    106     |
| 2022-01-31 |   Cook  | Illinois | 17031 | 1080784 | 13897  |    5438    |    102     |
| 2020-05-27 |   Cook  | Illinois | 17031 |  74521  |  3455  |    702     |    101     |
+------------+---------+----------+-------+---------+--------+------------+------------+
Truncated to displaylimit of 10.

### Most deaths reported by each county in IL

In [129]:
%%sql
-- Creating the table holding valus for Illinois
WITH 
illinois_2020 AS (select * from us_counties_2020 where state = 'Illinois'),
illinois_2021 AS (select * from us_counties_2021 where state = 'Illinois'),
illinois_2022 AS (select * from us_counties_2022 where state = 'Illinois'),
illinois_2023 AS (select * from us_counties_2023 where state = 'Illinois'),
illinois AS (select * from illinois_2020 UNION select * from illinois_2021 UNION select * from illinois_2022 UNION select * from illinois_2023),
data as ( select *, ROW_NUMBER() OVER(PARTITION BY COUNTY ORDER BY DAILYDEATHS DESC) as ROWS
from 
( select *,  
       COALESCE(cases - lag(cases) OVER(ORDER BY COUNTY, DATE), 0) as DailyCases,
       COALESCE(deaths - lag(deaths) OVER(ORDER BY COUNTY, DATE), 0) as DailyDeaths
from illinois
order by DailyDeaths desc))

select * from data
where ROWS = 1
order by DailyDeaths desc

Running query in 'duckdb:///covidandusa.duck.db'

+------------+------------+----------+-------+--------+--------+------------+-------------+------+
|    date    |   county   |  state   |  fips | cases  | deaths | DailyCases | DailyDeaths | ROWS |
+------------+------------+----------+-------+--------+--------+------------+-------------+------+
| 2020-06-08 |  Unknown   | Illinois |  None |  724   |  178   |    640     |     178     |  1   |
| 2020-11-06 |    Cook    | Illinois | 17031 | 210266 |  5742  |    5289    |     168     |  1   |
| 2020-11-06 |   DuPage   | Illinois | 17043 | 28834  |  675   |    1250    |      41     |  1   |
| 2022-11-11 |  Jackson   | Illinois | 17077 | 19167  |  167   |     0      |      25     |  1   |
| 2022-11-11 | Stephenson | Illinois | 17177 | 14104  |  218   |     0      |      24     |  1   |
| 2022-11-11 |   Shelby   | Illinois | 17173 |  7218  |  104   |     0      |      21     |  1   |
| 2022-01-14 |  Kankakee  | Illinois | 17091 | 25652  |  339   |    213     |      21     |  1   |
| 2020-11-06 |    Will    | Illinois | 17197 | 23279  |  473   |    956     |      21     |  1   |
| 2020-05-27 |    Lake    | Illinois | 17097 |  7845  |  270   |     78     |      20     |  1   |
| 2022-11-11 |    Pike    | Illinois | 17149 |  5851  |   90   |     0      |      17     |  1   |
+------------+------------+----------+-------+--------+--------+------------+-------------+------+
Truncated to displaylimit of 10.

### Most deaths reported by each county in Wisconsin

In [112]:
%%sql
-- Creating the table holding valus for Milwaukee in Wisconsin
WITH 
wisconsin_2020 AS (select * from us_counties_2020 where state = 'Wisconsin'),
wisconsin_2021 AS (select * from us_counties_2021 where state = 'Wisconsin'),
wisconsin_2022 AS (select * from us_counties_2022 where state = 'Wisconsin'),
wisconsin_2023 AS (select * from us_counties_2023 where state = 'Wisconsin'),
wisconsin AS (select * from wisconsin_2020 UNION select * from wisconsin_2021 UNION select * from wisconsin_2022 UNION select * from wisconsin_2023),
data as ( select *, ROW_NUMBER() OVER(PARTITION BY COUNTY ORDER BY DAILYDEATHS DESC) as ROWS
from 
( select *,  
       COALESCE(cases - lag(cases) OVER(ORDER BY COUNTY, DATE), 0) as DailyCases,
       COALESCE(deaths - lag(deaths) OVER(ORDER BY COUNTY, DATE), 0) as DailyDeaths
from wisconsin
order by DailyDeaths desc))

select * exclude(ROWS) from data
where ROWS = 1
order by DailyDeaths desc

Running query in 'duckdb:///covidandusa.duck.db'

+------------+-----------+-----------+-------+--------+--------+------------+-------------+
|    date    |   county  |   state   |  fips | cases  | deaths | DailyCases | DailyDeaths |
+------------+-----------+-----------+-------+--------+--------+------------+-------------+
| 2021-01-16 | Milwaukee | Wisconsin | 55079 | 99152  |  1103  |    357     |      74     |
| 2022-01-27 | Sheboygan | Wisconsin | 55117 | 30567  |  262   |    304     |      38     |
| 2021-02-25 | Jefferson | Wisconsin | 55055 |  8801  |  125   |     7      |      38     |
| 2020-12-22 |    Dane   | Wisconsin | 55025 | 33019  |  169   |     93     |      27     |
| 2022-11-11 |  Douglas  | Wisconsin | 55031 | 13796  |  109   |     1      |      24     |
| 2022-01-24 |  Waukesha | Wisconsin | 55133 | 105649 |  908   |    1362    |      23     |
| 2022-01-12 |   Racine  | Wisconsin | 55101 | 47558  |  549   |    874     |      16     |
| 2022-11-11 |  Burnett  | Wisconsin | 55013 |  4879  |   60   |     5      |      15     |
| 2020-11-12 |   Barron  | Wisconsin | 55005 |  2171  |   28   |     77     |      14     |
| 2021-12-23 |   Dodge   | Wisconsin | 55027 | 19668  |  263   |    109     |      13     |
+------------+-----------+-----------+-------+--------+--------+------------+-------------+
Truncated to displaylimit of 10.

### Adding Column - Region based on the state

In [125]:
%%sql

select *, case when state in ('West Virginia', 'District of Columbia', 'Maryland', 'Virginia', 'Kentucky', 'Tennessee', 'North Carolina', 'Mississippi', 'Arkansas', 'Louisiana', 'Alabama', 'Georgia', 'South Carolina', 'Florida', 'Delaware') THEN 'SOUTH'
               when state in ('Arizona', 'New Mexico', 'Oklahoma', 'Texas') THEN 'SOUTHWEST'
               when state in ('Washington', 'Oregon', 'California', 'Nevada', 'Idaho', 'Montana', 'Wyoming', 'Utah', 'Colorado', 'Alaska', 'Hawaii') THEN 'WEST'
               when state in ('North Dakota', 'South Dakota', 'Nebraska', 'Kansas', 'Minnesota', 'Iowa', 'Missouri', 'Wisconsin', 'Illinois', 'Michigan', 'Indiana', 'Ohio') THEN 'MIDWEST'
               when state in ('Maine', 'Vermont', 'New York', 'New Hampshire', 'Massachusetts', 'Rhode Island', 'Connecticut', 'New Jersey', 'Pennsylvania') THEN 'NORTHEAST'
               ELSE 'NOIDEA' END as REGION
from us_counties_2020

Running query in 'duckdb:///covidandusa.duck.db'

+------------+-------------+------------+-------+-------+--------+-----------+
|    date    |    county   |   state    |  fips | cases | deaths |   REGION  |
+------------+-------------+------------+-------+-------+--------+-----------+
| 2020-01-21 |  Snohomish  | Washington | 53061 |   1   |   0    |    WEST   |
| 2020-01-22 |  Snohomish  | Washington | 53061 |   1   |   0    |    WEST   |
| 2020-01-23 |  Snohomish  | Washington | 53061 |   1   |   0    |    WEST   |
| 2020-01-24 |     Cook    |  Illinois  | 17031 |   1   |   0    |  MIDWEST  |
| 2020-01-24 |  Snohomish  | Washington | 53061 |   1   |   0    |    WEST   |
| 2020-01-25 |    Orange   | California | 06059 |   1   |   0    |    WEST   |
| 2020-01-25 |     Cook    |  Illinois  | 17031 |   1   |   0    |  MIDWEST  |
| 2020-01-25 |  Snohomish  | Washington | 53061 |   1   |   0    |    WEST   |
| 2020-01-26 |   Maricopa  |  Arizona   | 04013 |   1   |   0    | SOUTHWEST |
| 2020-01-26 | Los Angeles | California | 06037 |   1   |   0    |    WEST   |
+------------+-------------+------------+-------+-------+--------+-----------+
Truncated to displaylimit of 10.

### Total Deaths and Cases in Each State

In [143]:
%%sql

WITH 
us_2020 AS (select * from us_counties_2020),
us_2021 AS (select * from us_counties_2021),
us_2022 AS (select * from us_counties_2022),
us_2023 AS (select * from us_counties_2023),
us AS (select * from us_2020 UNION select * from us_2021 UNION select * from us_2022 UNION select * from us_2023),
daily as (select *, COALESCE(cases - lag(cases) OVER(PARTITION BY STATE, COUNTY ORDER BY DATE), 0) as DailyCases, COALESCE(deaths - lag(deaths) OVER(PARTITION BY STATE, COUNTY ORDER BY DATE), 0) as DailyDeaths from us)
select state, sum(Dailycases) as TotalCases, sum(DailyDeaths) as TotalDeaths
from daily
group by state

Running query in 'duckdb:///covidandusa.duck.db'

+--------------------------+------------+-------------+
|          state           | TotalCases | TotalDeaths |
+--------------------------+------------+-------------+
|           Iowa           |   907309   |    10770    |
|          Kansas          |   940690   |    10392    |
|        Louisiana         |  1580617   |    18834    |
|           Ohio           |  3415145   |    42065    |
|          Texas           |  8446835   |    94516    |
|         Arizona          |  2451060   |    33187    |
|       Rhode Island       |   461720   |     3915    |
| Northern Mariana Islands |   13365    |      39     |
|       Puerto Rico        |  1137443   |     5848    |
|        Tennessee         |  2459032   |    29035    |
+--------------------------+------------+-------------+
Truncated to displaylimit of 10.